//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

pub mod prelude;

pub mod alert_notification;
pub mod chain;
pub mod crawler;
pub mod destination_registration_proposal;
pub mod telegram_chat_id;
pub mod user_alert;
pub mod user_destination;
