//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

pub use super::alert_notification::Entity as AlertNotification;
pub use super::chain::Entity as Chain;
pub use super::crawler::Entity as Crawler;
pub use super::destination_registration_proposal::Entity as DestinationRegistrationProposal;
pub use super::telegram_chat_id::Entity as TelegramChatId;
pub use super::user_alert::Entity as UserAlert;
pub use super::user_destination::Entity as UserDestination;
